apiVersion: kubelet.config.k8s.io/v1beta1
kind: CredentialProviderConfig
providers:
  - name: yc-credential-provider
    apiVersion: credentialprovider.kubelet.k8s.io/v1
    matchImages:
      - "cr.yandex"
      - "cr.cloud.yandex.net"
      - "container-registry.cloud.yandex.net"
    defaultCacheDuration: "1h"
